### ISSUE TITLE
Can you give me some advice?

### ISSUE THREAD

**Issue by wahoyi** [saurabh10041998/tcpliveplay#1]
I tried to use your script as a client to perform a replay attack, but the client always sends TCP Reset when sending the third packet, then there will be some TCP retransmission, out of order and other errors, so it cannot successfully establish an available TCP connection, if you can give me some advice, I would appreciate it.

**Comment by saurabh10041998** [comment]
Hi @wahoyi, Thank you so much for playing around with the script. 
I have **updated the fix in the script in latest merge** (please check master branch) . Please do `git pull` and you are good to go.
I hope you are running linux (or some sort of unix operating system). Please make sure some of below things are followed.

1. Script must be run as root,  since scapy requires root access.
2. Source ip must be same as that of the interface on which you are replaying the packet ( This is just required to view the response sent by server)
3. Your pcap file must have complete tcp stream ( at least SYN, ACK messages/packets to complete the handshake). 

Again this script is _work in progress_, so I do appreciate the any feedbacks and concerns..

Please let me know if anything else is required and Thanks Again 🙂.

**Comment by wahoyi** [comment]
Hello! @saurabh10041998, thank you for your reply,  I tried many times and found that the problem maybe was not with the script, but with the server I was trying to attack. Although I was unsuccessful, thank you for your reply again.

**Comment by saurabh10041998** [comment]
Okay.. I am closing this issue then. In case if I get any info, I further look into this in future.. Thanks again 💯
