### ISSUE TITLE
Error "Ether" not found

### ISSUE THREAD

**Issue by tuxflo** [saurabh10041998/tcpliveplay#5]
Hi!
I wanted to try the script since it looks like exactly what I was looking for.
However when I try to run it with a simple example like described in the Readme I get the following error:
```
./tcp-exec.py -f test.pcap -i lo -s 127.0.0.1 -d 127.0.0.1 --sport=4444 --dport=50100
Traceback (most recent call last):
  File "/home/flo/workdir/tcpliveplay/./tcp-exec.py", line 154, in <module>
    replay(pcap_file_path,iface)
  File "/home/flo/workdir/tcpliveplay/./tcp-exec.py", line 87, in replay
    eth = p[Ether]
  File "/usr/local/lib/python3.10/dist-packages/scapy/packet.py", line 1327, in __getitem__
    raise IndexError("Layer [%s] not found" % name)
IndexError: Layer [Ether] not found
```
I think `Ether` should come from scapy which I installed via `pip install scapy`. The version it pulled from pypi is 2.5.0, so I wonder if this script requires a specific scapy version?

**Comment by saurabh10041998** [comment]
Hello @tuxflo , Thank you so much for reporting this !!
I am very much interested in looking at the sample packet from `test.pcap` you are using for replaying, since this error points to the **absence of Ethernet layer** (802.11) in tcp packet.

Currently script supports TCP packets composed on top of following layer 2 protocols
1. Ethernet (802.11 frame)
2. Linux Cooked Capture (SLL)

Can you please let me know what is layer 2 protocols  used by packets in `test.pcap` ? (This can be done by observing packet in wireshark / tshark )
That will be big help for me to narrow down the issue.

Thank you so much again !!

**Comment by tuxflo** [comment]
I took a closer look at the pcap file using wireshark and you were totally right. The pcap didn't contain the Ethernet frames. Maybe because I used tcpdump in WSL to capture the traffice. When using tcpdump on a native Linux server it worked as expected.
Thanks for the hint!
